### PR TITLE
Top menu icon navigation/79

### PR DESCRIPTION
**Pull request by ishandongol**

### CODE REVIEW

**Comment by cliftonmcintosh** [comment]
Screenshot from browser:

top-nav-sample

**Review by cliftonmcintosh — COMMENTED** [review]
@ishandongol 

Looks very nice! Thank you.

Small thing: would you be willing to add newlines to the ends of the three new files?

**Comment by ishandongol** [comment]
Sure, no problem.

**Comment by ishandongol** [comment]
@cliftonmcintosh I have updated the files.

**Review by cliftonmcintosh — APPROVED** [review]

**Comment by cliftonmcintosh** [comment]
@ishandongol 

Thank you very much!

**Comment by cliftonmcintosh** [comment]
@ishandongol 

Your change has been deployed to https://beta.nepalmap.org.

It is a nice enhancement.

nav-on-beta-server

**Comment by ishandongol** [comment]
Wow, Thank you so much.

**Pull request merged**
