### PR TITLE
fix topojson files to match database entries

### PR DESCRIPTION
**Pull request by openrijal**
this fixes the issue for loading map in the data page

### CODE REVIEW

**Comment by cliftonmcintosh** [comment]
Looks good, @crackjack 

Thank you for the fix.

I have a request. Can I suggest we not include the req.txt file? If you think it would be valuable information, would you consider moving it into the README or the project wiki?

**Comment by openrijal** [comment]
oops soory, my bad, didn't mean to include it. I'll remove it.

**Comment by cliftonmcintosh** [comment]
@crackjack

Once you've removed that file, this PR should be good to go

**Comment by openrijal** [comment]
@cliftonmcintosh I just updated it. good to go.

**Review by cliftonmcintosh — APPROVED** [review]

**Pull request merged**
