### PR TITLE
Federal structure

### PR DESCRIPTION
**Pull request by openrijal**

### CODE REVIEW

**Review by cliftonmcintosh — CHANGES_REQUESTED** [review]
@crackjack 

Thank you for starting working on this. The geojson file needs to be manipulated so that it conforms to the structure required by the wazimap framework that we use. In particular, the `properties` element for each local geographic body needs to be changed. The directions on #5 describe what is needed. Please take a look at the directions again. There is a link to a README in the pre-federal project that describes what is needed.

The current "properties" element for each local body in the geojson in this pull request will not work with Wazimap. It needs to have:
- a `geoid` that is unique to the local level. All 753 local units will have a unique code, perhaps something like "local-1", "local-2", etc.
- a `name` (lowercase key, not`NAME`) field that is the common name that should be displayed
- a `code` field that is the number part of the `geoid`. For example, a local unit with a `geoid` of "local-1" would have a `code` of "1".
- a `level` (lowercase key, not `LEVEL`) field is "local" for all 753 local bodies, regardless of the type of local body. For the Wazimap framework, they are all at the same level. It will not allow us to distinguish different types of local unit.
- other keys can be included, but they will be ignored by the Wazimap framework. You might, for example, choose to keep the `DISTRICT` key because it might make it easier to build the SQL we need. The SQL data will need to include a parent `geoid` for each local unit.

Here is an example of what that might look like:
`{"geoid": "local-3", "name": "Bhaktapur", "code": "3", "level": "local"}`

This is what it currently looks like and this is what needs replacing:
`{ "id": null, "F_ID": 104, "N_ID": "bhaktapur-bhaktapur", "NAME": "Bhaktapur", "LEVEL": "Nagarpalika", "DISTRICT": "Bhaktapur" }`

This process must be done for districts and provinces as well. Please see the geojson files in the pre-federal project for examples of how it should be done.

**Comment by openrijal** [comment]
I have modified the script and got an output file with properties like below
`{"code": "105", "name": "Madhyapur Thimi", "geoid": "local-105", "level": "local", "division": "Nagarpalika", "parent": "Bhaktapur"}`

I made the `code` from `F_ID`, `geoid` from `code` and `level`, also added keys like `division` and `parent`

Is there a requirement that the code should start from 1? or can it be any unique integer?

If this works, I'll convert all other files accordingly.

**Comment by cliftonmcintosh** [comment]
Any unique integer is fine

**Comment by openrijal** [comment]
this is how the district looks like
`{"code": "1581", "name": "jhapa", "geoid": "district-1581", "level": "district"}`

**Comment by openrijal** [comment]
this is how the province properties look
`{"code": "6", "name": "Province No. 6", "geoid": "province-6", "level": "province"}`

**Comment by openrijal** [comment]
updated PR

**Comment by cliftonmcintosh** [comment]
@crackjack 

Can you share the script you used to update the files by making a PR to the [maptools repo](https://github.com/Code4Nepal/maptools)? We have been putting our scripts there rather than in the main repo.

**Comment by cliftonmcintosh** [comment]
@crackjack 

Some questions and comments.

- For clarity, can we do each level as a separate PR? There are issues for the districts (#4), and province (#3). I will create an issue for adding the country level files.
- We don't need to keep the OKPN files. We just need the transformed ones.
- If districts have the exact same boundaries as before, can we re-use the old district geo files? Or at least use the same geoids for districts. That is because we have a lot of district-level data that we can transfer over. If we use new geoids for districts, we will have to re-process all of those data.
- The names of each unit should be capitalized. (The names in the district files in this PR are currently lowercase.)

**Review by cliftonmcintosh — APPROVED** [review]
Looks good. Thanks for doing this.

**Pull request merged**
