### PR TITLE
Add link to the national data portal under household data

### LINKED ISSUE #64: Add a link to the original data set for each profile section
For each section in the profile, add a link to the original data set to allow users to double-check our work and to provide more accountability and transparency. For example, the Households summary would have a link to the National Data Profile (http://nationaldata.gov.np) underneath the section where the total number of households is shown in NepalMap. Links should be as specific as possible but can be more general when specificity is not possible. For example, we do not currently have the ability to link to the National Data Profile pages for a specific locality or district or province, so a link to the main National Data Profile page is appropriate.

### PR DESCRIPTION
**Pull request by amitness**
Resolves #64

### CODE REVIEW

**Review by cliftonmcintosh — CHANGES_REQUESTED** [review]
I would suggest putting this in the first section in the households, between lines 19 and 20. Then it's in the same section where households start. To me, that's easier to find and more likely to communicate that it is for all the statistics. When it is at the end, it is harder to find and it looks like it might be the link only for the last statistic presented. If you move it to the first section, it will look like this:

link-at-start-of-households

It could also go right after the header for the section (between lines 4 and 5). If so, it would look like this:
link-after-household-header

I have a slight preference for the first place (at the bottom of the first section).

**Comment by amitness** [comment]
@cliftonmcintosh Sure, I've moved it to the summary section for the household data. Please review now.

**Review by cliftonmcintosh — APPROVED** [review]
Thank you!

**Comment by cliftonmcintosh** [comment]
@amitness 

Thank you for the updates. Your updates are now visible at https://beta.nepalmap.org.

**Pull request merged**
