### PR TITLE
Requires Review: Displays Nepali number system

### PR DESCRIPTION
**Pull request by pratimakandel**
@cliftonmcintosh

### CODE REVIEW

**Comment by cliftonmcintosh** [comment]
@pratimakandel 

There is a small merge conflict. Can you please resolve the conflict by merging `Code4Nepal:dev` into your branch?

**Comment by pratimakandel** [comment]
@cliftonmcintosh 

I just did it! Let me know if it is fixed.

**Comment by cliftonmcintosh** [comment]
@pratimakandel 

Thank you for the update. I am having trouble running your `dev` branch in order to verify the changes. When I check it out and try to load data using `cat sql/*.sql | psql -U wazimap_np -W wazimap_np`, the data load fails with

```
(1 row)

SET
SET
SET
ALTER TABLE
DROP TABLE
SET
SET
CREATE TABLE
ALTER TABLE
ERROR:  missing data for column "geo_level"
CONTEXT:  COPY population, line 1719: ""
ALTER TABLE
```

Here are the steps I have taken:
1. start with a fresh database by:
  - dropping the wazimap_np database
  - creating the wazimap_np database
  - granting permissions on that database to the wazimap_np user
2. run `python manage.py migrate`
3. run `cat sql/*.sql | psql -U wazimap_np -W wazimap_np`

Is there something out of sync between `Code4Nepal:dev` and `pratimakandel:dev`? Can you run those commands without getting an error?

~I have also tried running in docker, but it is not starting up correctly. I believe that is because `pratimakandel:dev` is out of sync with `Code4Nepal:dev`. For example, I am getting an error about trying to cat simple tables. `Code4Nepal:dev` does not do that (because we removed the command for that).~

(After updating to your latest, https://github.com/Code4Nepal/nepalmap_federal/pull/76/commits/4ea3cccffe51ee07c4567d7e3f5fb1b8f1fb733b, I can get it to run in docker.)

**Comment by pratimakandel** [comment]
@cliftonmcintosh 
What about now? My dev branch is up-to-date and I ran the following commands, I could successfully run the server with my branch

**Comment by cliftonmcintosh** [comment]
@pratimakandel 

Thank you. It looks good.

Yes, I can run in docker now after updating to your latest update. I have confirmed that the number formatting has been updated. One interesting thing is that the old format continues to be present in the tables that are opened up in the profile view (with the "Show data" link) and the table views (like http://localhost:8000/data/table/?table=AGRICULTURE_LAND_USE&geo_ids=province-6,country-NP&primary_geo_id=province-6#valueType%7Cestimate). I have no idea how to change those and would not suggest that that be changed as part of this PR.

number-format-update

table-view

**Comment by pratimakandel** [comment]
@cliftonmcintosh 
Great!! I completely forgot about the show data section. But I can look at it and see of there is a way.  
Thanks.

**Comment by cliftonmcintosh** [comment]
@pratimakandel 

https://beta.nepalmap.org has been updated with your changes. Thank you!

**Pull request merged**
