### PR TITLE
[ENHANCEMENTS] dsign fixes

### PR DESCRIPTION
**Pull request by ishandongol**
# Enhancements

- fixed the modal design
	- the width of the modal is 100% for smaller devices
	- and is vertically scrollable
- fixed the profile details cover profile card
	- added background color to white
	- added extra top margin for smaller devices

### CODE REVIEW

**Comment by cliftonmcintosh** [comment]
@ishandongol 

Thank you. It looks much better! One thing I noticed is that the main profile card (the one that goes with the map at the top) is white in a wider screen but matches the grey on the background on a smaller screen. Would we want the tile to be white on smaller devices like it is on a wider screen or is this a deliberate choice to make it feel like it's not sitting on top? Screenshots here:

Wider screen
top-tile-wide

Smaller screen
top-tile

**Review by cliftonmcintosh — APPROVED** [review]
Thank you! This is a definite improvement. If the color of the main tile on a smaller screen should be white, I suggest we can do that in a separate PR.

**Comment by cliftonmcintosh** [comment]
@ishandongol 

When I deployed this to beta.nepalmap.org, the top tile is white. I'm not sure why it didn't display correctly when I ran it on my laptop earlier.

Here is a screenshot of https://beta.nepalmap.org/profiles/district-41-makwanpur/ in desktop Chrome that has been sized down as well as a screenshot from my phone.

white-top-tile
Makwanpur

**Comment by cliftonmcintosh** [comment]
This has been deployed to https://beta.nepalmap.org.

**Comment by ishandongol** [comment]
We need to compile the sass file. I guess you forgot to run compilescss in
local.

Will look further into the issue.

**Pull request merged**
