### PR TITLE
Province 5  issues#37 fixed 

### PR DESCRIPTION
**Pull request by pratimakandel**

### CODE REVIEW

**Comment by pratimakandel** [comment]
Province 4 issue #36 fixed

**Comment by pratimakandel** [comment]
Province 1 issue #35 fixed

**Comment by pratimakandel** [comment]
Issues #33 and Issues #34 fixed

**Review by cliftonmcintosh — APPROVED** [review]

**Comment by cliftonmcintosh** [comment]
@pratimakandel 

Thank you!

**Pull request merged**
